title: Venkata Sai Teja Yerramsetti
description: Backend Software Engineer | Systems Design | AI/ML Integration
theme: jekyll-theme-minimal
email: venkatasaitejayerramsetti@gmail.com
# Provide the path to your social links
linkedin_username: www.linkedin.com/in/venkata-yerramsetti-595511172
